/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 scene.gltf 
Author: trivial.cat (https://sketchfab.com/trivial.cat)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/gaz-52-truck-new-version-6fee4fb6860d4931b3ac2d4b7f2a1723
Title: Gaz-52 truck, new version
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/scene.gltf");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            geometry={nodes.defaultMaterial.geometry}
            material={materials.Cabin}
            position={[-277.568, 94.143, 120.227]}
            scale={2.819}
          />
          <mesh
            geometry={nodes.defaultMaterial_1.geometry}
            material={materials.Details}
            position={[-277.568, 94.143, 120.227]}
            scale={2.819}
          />
          <mesh
            geometry={nodes.defaultMaterial_2.geometry}
            material={materials.Back}
            position={[-277.568, 94.143, 120.227]}
            scale={2.819}
          />
          <mesh
            geometry={nodes.defaultMaterial_3.geometry}
            material={materials.glass}
            position={[-299.534, 116.15, 91.034]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/scene.gltf");
