/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 katana.gltf 
Author: gkari (https://sketchfab.com/gkari)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/katana-onimaru-kunitsuna-valorant-73ae18bf62f249f9ba6a3824201ce8b0
Title: Katana Onimaru Kunitsuna Valorant
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/katana.gltf");
  return (
    <group {...props} dispose={null}>
      <group
        position={[3.844, 5.335, -0.96]}
        rotation={[-Math.PI / 2, -0.291, -Math.PI / 2]}
        scale={[0.231, 0.203, 0.322]}
      >
        <mesh geometry={nodes.Object_16.geometry} material={materials.metall} />
        <mesh
          geometry={nodes.Object_17.geometry}
          material={materials.material_0}
        />
      </group>
      <mesh
        geometry={nodes.Object_4.geometry}
        material={materials.black_kv}
        position={[4.042, 0.965, -0.067]}
        rotation={[-Math.PI / 2, -1.183, -Math.PI / 2]}
        scale={[0.373, 0.332, 1.408]}
      />
      <mesh
        geometry={nodes.Object_6.geometry}
        material={materials.pink_metall}
        position={[2.453, 1.649, -0.071]}
        rotation={[Math.PI / 2, 1.132, Math.PI / 2]}
        scale={[0.293, 0.403, 0.037]}
      />
      <mesh
        geometry={nodes.Object_8.geometry}
        material={materials.pink_metall}
        position={[2.414, 1.664, -0.067]}
        rotation={[Math.PI / 2, -0.443, Math.PI / 2]}
        scale={[0.546, 1, 1]}
      />
      <mesh
        geometry={nodes.Object_10.geometry}
        material={materials.metall}
        position={[2.423, 1.66, -0.368]}
        rotation={[Math.PI / 2, -0.447, -Math.PI / 2]}
        scale={[0.612, 1.092, 0.662]}
      />
      <mesh
        geometry={nodes.Object_12.geometry}
        material={materials.dark_pink_mouth}
        position={[1.972, 1.875, -0.071]}
        rotation={[Math.PI / 2, 1.132, Math.PI / 2]}
        scale={[0.1, 0.367, 0.374]}
      />
      <mesh
        geometry={nodes.Object_14.geometry}
        material={materials.green_light}
        position={[-4.956, 0.951, -0.96]}
        rotation={[-Math.PI / 2, -0.291, -Math.PI / 2]}
        scale={[0.225, 0.203, 0.314]}
      />
      <mesh
        geometry={nodes.Object_19.geometry}
        material={materials.metall}
        position={[-5.228, 0.879, -0.96]}
        rotation={[-Math.PI / 2, -0.301, -Math.PI / 2]}
        scale={[0.231, 0.056, 0.312]}
      />
      <mesh
        geometry={nodes.Object_21.geometry}
        material={materials.metall}
        position={[-1.374, 2.287, -0.849]}
        rotation={[-Math.PI / 2, -0.726, -Math.PI]}
        scale={[0.342, 0.118, 0.342]}
      />
      <mesh
        geometry={nodes.Object_23.geometry}
        material={materials.black_kv}
        position={[2.188, 4.205, -0.754]}
        rotation={[-Math.PI / 2, -0.291, Math.PI]}
        scale={[0.249, 0.03, 0.249]}
      />
      <mesh
        geometry={nodes.Object_25.geometry}
        material={materials.green_lenta}
        position={[2.568, 4.521, -0.726]}
        rotation={[-Math.PI / 2, -0.309, Math.PI]}
        scale={[1, 1, 0.912]}
      />
      <mesh
        geometry={nodes.Object_27.geometry}
        material={materials.green_lenta}
        position={[1.6, 3.826, 0.368]}
        rotation={[-Math.PI / 2, -0.291, Math.PI]}
        scale={[0.202, 1, 1]}
      />
      <mesh
        geometry={nodes.Object_29.geometry}
        material={materials.green_lenta}
        position={[2.954, 4.311, -0.687]}
        rotation={[-1.738, -0.5, 3.093]}
        scale={0.229}
      />
      <mesh
        geometry={nodes.Object_31.geometry}
        material={materials.green_lenta}
        position={[3.913, 4.736, -1.037]}
        rotation={[1.861, 0.284, -0.558]}
        scale={[0.17, 0.197, 0.169]}
      />
      <mesh
        geometry={nodes.Object_33.geometry}
        material={materials.metall}
        position={[2.591, 1.58, -0.067]}
        rotation={[-Math.PI / 2, -1.155, -Math.PI / 2]}
        scale={[0.266, 0.369, 0.113]}
      />
      <mesh
        geometry={nodes.Object_35.geometry}
        material={materials.GOLD}
        position={[1.152, 2.382, -0.067]}
        rotation={[Math.PI / 2, -0.43, Math.PI / 2]}
        scale={[0.174, 0.058, 0.224]}
      />
      <mesh
        geometry={nodes.Object_37.geometry}
        material={materials.pink_metall}
        position={[2.265, 1.736, 0.275]}
        rotation={[0.176, 0.353, 1.091]}
        scale={[0.063, 0.04, 0.248]}
      />
      <mesh
        geometry={nodes.Object_39.geometry}
        material={materials.metall}
        position={[1.004, 2.39, -0.067]}
        rotation={[Math.PI / 2, -0.43, Math.PI / 2]}
        scale={[0.111, 0.101, 0.085]}
      />
      <mesh
        geometry={nodes.Object_41.geometry}
        material={materials.black_kv}
        position={[2.756, 1.388, 0.124]}
        rotation={[-Math.PI / 2, -0.341, -Math.PI / 2]}
        scale={[1.199, 1.199, 1.338]}
      />
      <mesh
        geometry={nodes.Object_43.geometry}
        material={materials.green_lenta}
        position={[3.09, 1.354, 0.27]}
        rotation={[-Math.PI / 2, -1.183, -Math.PI]}
      />
      <mesh
        geometry={nodes.Object_45.geometry}
        material={materials.green_lenta}
        position={[4.914, 0.609, 0.296]}
        rotation={[-Math.PI / 2, -1.183, -Math.PI]}
      />
      <mesh
        geometry={nodes.Object_47.geometry}
        material={materials.green_lenta}
        position={[5.5, 0.342, -0.067]}
        rotation={[0, 0, -1.892]}
        scale={[0.054, 1.231, 1]}
      />
      <mesh
        geometry={nodes.Object_49.geometry}
        material={materials.eyes}
        position={[1.232, 2.249, 0.233]}
        rotation={[Math.PI / 2, -0.448, 1.583]}
        scale={[0.031, 0.112, 0.051]}
      />
      <mesh
        geometry={nodes.Object_51.geometry}
        material={materials.pink_metall}
        position={[1.945, 1.708, 0.075]}
        rotation={[-0.702, 0.54, -2.208]}
        scale={[0.058, 0.123, 0.06]}
      />
      <mesh
        geometry={nodes.Object_53.geometry}
        material={materials.teeth}
        position={[2.143, 1.932, 0.14]}
        rotation={[0.796, -0.302, 1.317]}
        scale={[0.013, 0.025, 0.021]}
      />
      <mesh
        geometry={nodes.Object_55.geometry}
        material={materials.demon}
        position={[1.819, 1.96, -0.053]}
        rotation={[Math.PI / 2, -0.448, 1.645]}
        scale={0.319}
      />
      <mesh
        geometry={nodes.Object_57.geometry}
        material={materials.metall}
        position={[5.465, 0.408, -0.067]}
        rotation={[-Math.PI / 2, -1.256, -Math.PI / 2]}
        scale={[1.134, 1.19, 1]}
      />
      <mesh
        geometry={nodes.Object_59.geometry}
        material={materials.metall}
        position={[3.451, 1.198, 0.106]}
        rotation={[Math.PI / 2, -1.173, Math.PI / 2]}
        scale={0.048}
      />
      <mesh
        geometry={nodes.Object_61.geometry}
        material={materials.metall}
        position={[3.518, 1.169, 0.093]}
        rotation={[-Math.PI / 2, -1.183, -Math.PI]}
        scale={[0.175, 0.06, 0.175]}
      />
    </group>
  );
}

useGLTF.preload("/katana.gltf");
